# Default application configuration.
---
The list of packages active for this application.

```no-highlight
packageList: [
]
```

Values for packages which correspond with the values provided by packages'
implementations of hook [`trussConfigServer`](../../hooks#trussconfigserver).

```no-highlight
packageConfig: {
}
```

The list of middleware that run in the bootstrap phase. This is where you
spin up HTTP/sockets/database/whatever else. The list contains the names of
packages which have an implementation of hook
[`trussBootstrapMiddleware`](../../hooks#trussbootstrapmiddleware).

```no-highlight
bootstrapMiddleware: [
]
```
