# Default application configuration.
---

## Package list

The list of packages active for this application.

```yaml
packageList:
```

### Development

Project documentation. Safe to disable on production.

```yaml
  - 'truss-dox'
```

### Production
REPL to control the application.

```yaml
  - 'truss-repl'
```

## Package configuration

Values for packages which correspond with the values provided by packages'
implementations of hook
[`trussServerPackageConfig`](../../hooks#trussserverpackageconfig).

```yaml
packageConfig: {
}
```

## Bootstrap middleware

The list of middleware that run in the bootstrap phase. This is where you
spin up your HTTP/socket server, or whatever else. The list contains the
names of packages which have an implementation of hook
[`trussServerBootstrapMiddleware`](../../hooks#trussserverbootstrapmiddleware).

```yaml
serverBootstrapMiddleware:
```

Spin up the REPL.

```yaml
  - 'truss-repl'
```
