# # Default application configuration.
# ---
#
# ## Package list
#
# The list of packages active for this application.
packageList:

  # ### Development
  #
  # Project documentation. Safe to disable on production.
  - 'truss-dox'

  # ### Production
  # REPL to control the application.
  - 'truss-repl'

# ## Package configuration
#
# Values for packages which correspond with the values provided by packages'
# implementations of hook
# [`trussServerPackageConfig`](../../hooks#trussserverpackageconfig).
packageConfig: {
}

# ## Bootstrap middleware
#
# The list of middleware that run in the bootstrap phase. This is where you
# spin up your HTTP/socket server, or whatever else. The list contains the
# names of packages which have an implementation of hook
# [`trussServerBootstrapMiddleware`](../../hooks#trussserverbootstrapmiddleware).
serverBootstrapMiddleware:

  # Spin up the REPL.
  - 'truss-repl'
