# # Default application configuration.
# ---
# The list of packages active for this application.
packageList: [
]

# Values for packages which correspond with the values provided by packages'
# implementations of hook [`trussConfigServer`](../../hooks#trussconfigserver).
packageConfig: {
}

# The list of middleware that run in the bootstrap phase. This is where you
# spin up HTTP/sockets/database/whatever else. The list contains the names of
# packages which have an implementation of hook
# [`trussBootstrapMiddleware`](../../hooks#trussbootstrapmiddleware).
bootstrapMiddleware: [
]
